### ISSUE TITLE
Small Punctuation Check in GROW Goal Setting Model

### ISSUE THREAD

**Issue by lasse-offerzen** [OfferZen-Community/developer-mentoring#119]
Heyo! 🚀 We've spotted one or two punctuation errors on [this page](https://www.developermentoring.guide/docs/essential-mentoring-resources/grow-goal-setting-model) of the guide—if someone could go into the markdown file and double-check that would be great! 🙏

**Comment by cryingcavecat** [comment]
I've done a quick look and found a couple of errors. Pull request made accordingly.

**Comment by lasse-offerzen** [comment]
Thanks @cryingcavecat !
