### ISSUE TITLE
Messy Scrolling Issue (See Clip)

### ISSUE THREAD

**Issue by lasse-offerzen** [OfferZen-Community/developer-mentoring#156]
We have a messy scrolling issue (see video); we'd really like the squishy "**Developer Mentoring Guide**" that appears when the navbar disappears to be removed 🙏 Eternal gratitude awaits anyone who can give this a fix!

https://user-images.githubusercontent.com/105852971/190357472-b8d47444-51d1-42a3-b4bc-7c62b3a0201b.mp4

**Comment by obitoo7** [comment]
Does you want your be fixed and should not from with scrolling
Is that what you want?

**Comment by lasse-offerzen** [comment]
Hey @obitoo7 ! Thanks for the message - we want the words "Developer Mentoring Guide" to not be there if that makes sense?
<img width="50" alt="Screenshot 2022-09-15 at 18 21 54" src="https://user-images.githubusercontent.com/105852971/190456585-1dbf98f4-cff0-4338-a3c9-d8190ca8e836.png">

**Comment by obitoo7** [comment]
> Hey @obitoo7 ! Thanks for the message - we want the words "Developer Mentoring Guide" to not be there if that makes sense?
> <img width="50" alt="Screenshot 2022-09-15 at 18 21 54" src="https://user-images.githubusercontent.com/105852971/190456585-1dbf98f4-cff0-4338-a3c9-d8190ca8e836.png">
> 

Okay I get so you want to remove that part I get it thanks for clearing me

**Comment by lasse-offerzen** [comment]
No problem @obitoo7 !
