### ISSUE TITLE
Add Creative Commons (CC) licence for content

### ISSUE THREAD

**Issue by lasse-offerzen** [OfferZen-Community/developer-mentoring#162]
We need to add a [CC](https://creativecommons.org/) license for our content—if anyone knows how to about doing this (some more information [here](https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license)), your help would be appreciated! ©

**Comment by cmarchena** [comment]
I think this issue is already solved, isn't it? @lasse-offerzen issue should be closed

**Comment by lasse-offerzen** [comment]
Thanks @cmarchena !
