### ISSUE TITLE
For Senior Devs: Need List of the Useful Courses/Resources that you Refer Juniors To 

### ISSUE THREAD

**Issue by lasse-offerzen** [OfferZen-Community/developer-mentoring#165]
Please let us know what resources or documentation you refer juniors to! (for example, front-end devs tell juniors to read through [MDN](https://developer.mozilla.org/en-US/)?)

**Comment by codedmachine111** [comment]
Hello @lasse-offerzen . I have a few documentations and resources which were recommended to me by my mentor while learning Reactjs. They help in productivity management and some helped me as a guide to front end development. I would love to contribute by adding these resources in a markdown file. Can i work on this as a hacktoberfest PR?

**Comment by lasse-offerzen** [comment]
Hey @codedmachine111 ! :) Feel free to work on this! Thank you very much!

**Comment by codedmachine111** [comment]
That's great! Do you want me to create a new markdown file for this? Also do I need to be assigned first or should I just create a PR after I'm done?

**Comment by lasse-offerzen** [comment]
Maybe a new file under the 'Essential Mentoring Resources Folder' could work? Creating a new pull request is fine, no need to be assigned to anything for this one :) 🚀
