### ISSUE TITLE
Scrollbar Colour Enhancement Feature 🙏 

### ISSUE THREAD

**Issue by lasse-offerzen** [OfferZen-Community/developer-mentoring#166]
Heyo! We're hoping to have selected pages on our scrollbar highlight like this (with the blue trim on the left):

![Screenshot 2022-09-27 at 14 36 41](https://user-images.githubusercontent.com/105852971/192528513-0cf70e65-9d95-46e7-ac47-f7c59c211b71.png)

This is an example taken from: [the react website](https://reactnative.dev/docs/using-a-listview)

**Comment by devluki** [comment]
Hi, can I fix it? Do you want to use any specific color?

**Comment by lasse-offerzen** [comment]
Hey @devluki , if you could that'd be great :D We're thinking #3796F4
