### ISSUE TITLE
Image not showing up in README.md on GitHub

### ISSUE THREAD

**Issue by lasse-offerzen** [OfferZen-Community/developer-mentoring#167]
The image we want to show is this one:

![mentoring-guide-contribution-process](https://user-images.githubusercontent.com/105852971/192535773-a9d93f36-0604-4ab5-b0f4-d064feb7e2ec.png)

However, it doesn't seem to be showing:

![Screenshot 2022-09-27 at 15 13 06](https://user-images.githubusercontent.com/105852971/192535966-c3d5a6b4-07e2-4b2b-af3d-e1631cd335b6.png)

Any help would be greatly appreciated! 🙏

**Comment by RohitRajvaidya5** [comment]
I want to contribute to this issue.

**Comment by lasse-offerzen** [comment]
@RohitRajvaidya5 ! That'd be great! We'd really appreciate it 🙏

**Comment by RohitRajvaidya5** [comment]
Thanks can you assign me on this issue?

**Comment by RohitRajvaidya5** [comment]
I just want to ask can you add "hacktoberfest accepted" tag so it can be valid for hacktoberfest2022
I am first time participant.

**Comment by lasse-offerzen** [comment]
No problem @RohitRajvaidya5 :)

**Comment by adi-uchiha** [comment]
I would like to work on this. I am participating in hacktoberfest2022

**Comment by lasse-offerzen** [comment]
Feel free @adi-uchiha !

**Comment by RohitRajvaidya5** [comment]
Done !!!

**Comment by adi-uchiha** [comment]
> you

It will be valid when your PR is "MERGED" by the maintainer. There is no need of any labels, that is just for better validation for the review bots of hacktoberfest

**Comment by RohitRajvaidya5** [comment]
May be you are right . I am just beginner just wanted to you know this.

**Comment by adi-uchiha** [comment]
I think @RohitRajvaidya5 was right there should be a 'hacktoberfest' label as well

**Comment by adi-uchiha** [comment]
![Screenshot_2022-10-03-15-23-58-175_com.android.chrome.jpg](https://user-images.githubusercontent.com/103348863/193550082-e58e3832-31b6-4146-a130-7fb0f8f59383.jpg)

Got it

**Comment by RohitRajvaidya5** [comment]
Totally correct 👍

**Comment by lasse-offerzen** [comment]
Thank you both for the help!
