### ISSUE TITLE
Attribution for Atomic Habits page

### ISSUE THREAD

**Issue by james-smith-za** [OfferZen-Community/developer-mentoring#175]
The page titled Atomic Habits is a fairly good summary of James Clear's book of the same name.

I feel as though it could benefit from a little bit of attribution, and perhaps a recommendation that the interested reader pick up a copy themselves. It's a great book.

Edit: I'm happy to make a PR myself, if the maintainers are in favour.

**Comment by lasse-offerzen** [comment]
Go ahead @james-smith-za ! :)
