### ISSUE TITLE
Change wording to include developer-adjacent fields

### ISSUE THREAD

**Issue by GoodGuyGroves** [OfferZen-Community/developer-mentoring#178]
Hi All!

This is related to [a thread](https://zatech.slack.com/archives/C1RAQ4G5U/p1677435461976609) on ZATech slack where we were considering bringing this initiative back but driven by the community.

Myself and a number of colleagues have used OfferZen for jobs that aren't strictly "Developer" jobs like DevOps and Cloud engineers. I, myself, am a Cloud and DevOps engineer and I am really interested in mentoring others who would like to pursue this career but many places in the developer mentoring guide, the language is specifically centered around "Developers".

Is it okay for us to change the wording to open it up to other developer-adjacent fields? I would be glad to take a first pass at this. :)

**Comment by lasse-offerzen** [comment]
Hey @GoodGuyGroves — seems like a helpful edit so let's try it out :)
