### ISSUE TITLE
The logo images aren't consistent, and they're not centred properly

### ISSUE THREAD

**Issue by suitophobia** [OfferZen-Community/developer-mentoring#181]

**Comment by mercy-manynge** [comment]
Hello is this issue still valid, I would like to contribute and which logo images are you referring to.
As I looked into the code I saw only 2 logo images which are 
![Screenshot 2024-03-27 at 14 07 48](https://github.com/OfferZen-Community/developer-mentoring/assets/119874462/1f440fff-4673-4d27-9bc7-03f04c63dbfe)

**Comment by suitophobia** [comment]
This isn't relevant anymore. Closing
