### ISSUE TITLE
Add grouped headings and sub heading, running parrallel to the mentoring journey

### ISSUE THREAD

**Issue by adrianjtempelhoff** [OfferZen-Community/developer-mentoring#34]
The journey broken down into steps/milestones with resources relating to each phase of the journey.
A comprehensive living document growing with the relationship, stimulating growth in the relationship and acting as a guide for future relationships.
@OfferZenThrive

**Comment by OfferZenThrive** [comment]
@adrianjtempelhoff 

Could the phases be:
- Getting to know your mentoring partner
- Walking the journey with your mentoring partner
- Closing off the mentoring partnership

Keen to hear your suggestions here. :)
