### ISSUE TITLE
Add White OZ logo for dark mode

### ISSUE THREAD

**Issue by OfferZenThrive** [OfferZen-Community/developer-mentoring#51]
The OfferZen logo in dark mode is black at the moment, we'd like to change it to white.
![OfferZen_Thrive_Logo_White](https://user-images.githubusercontent.com/101867656/170712657-34c8f85a-a3b3-4264-be21-eb0e49bf3349.png)

**Comment by pololeningcelaya** [comment]
Hi! Can I take this issue?

**Comment by pololeningcelaya** [comment]
Well, I've already solve the issue and submitted the pull request. Hope it works for you!
