### ISSUE TITLE
Add GitHub icon with no. of stars on each page

### ISSUE THREAD

**Issue by OfferZenThrive** [OfferZen-Community/developer-mentoring#55]
See example:
![Screenshot 2022-05-27 at 16 02 35](https://user-images.githubusercontent.com/101867656/170715065-ad1c1716-cd92-450f-9df6-877a8f27cbf7.png)

**Comment by kermanp22** [comment]
<a class="github-button" href="https://github.com/OfferZen-Community/developer-mentoring" data-size="large" data-show-count="true" aria-label="Star OfferZen-Community/developer-mentoring on GitHub">Star</a>
