### ISSUE TITLE
Dark mode font colour is not in line with the design

### ISSUE THREAD

**Issue by suitophobia** [OfferZen-Community/developer-mentoring#71]
The dark mode colour being used should be: #2F96F4

**Comment by yoshitaka7** [comment]
@suitophobia 
Hi,I would like to contribute to this issue.
Is it the whole that you just want to change? Or is it just one part somewhere?

**Comment by suitophobia** [comment]
Hi! Thanks for your reply! It's just for the text highlights for active
links etc. It is basically to replace the colour that's there currently
(not the white). Excuse the brevity of this reply please, I'm replying from
my phone.

**Comment by yoshitaka7** [comment]
@suitophobia 
Thanks for the reply!
But I still don't know what the specific modifications are, so I'd like to see the design.

**Comment by rikusv** [comment]
@yoshitaka7 I think the green hyperlinks when in dark mode should be changed to #2F96F4 - @suitophobia please confirm whether that is correct.

**Comment by suitophobia** [comment]
That's correct :)

**Comment by yoshitaka7** [comment]
@rikusv @suitophobia 
Thank you both kindly!
I created a PR for you, so take a look at it!
https://github.com/OfferZen-Community/developer-mentoring/pull/79

**Comment by lasse-offerzen** [comment]
Thanks for all your help with this @yoshitaka7 💪
