### ISSUE TITLE
Change favicon to white when browser is in dark mode

### ISSUE THREAD

**Issue by OfferZenThrive** [OfferZen-Community/developer-mentoring#74]
The current favicon is black/dark grey which disappears when the browser is in dark mode.
- We'd like to replace it with the white favicon when in dark mode

![filecut_1156x1156](https://user-images.githubusercontent.com/101867656/172852588-7f17c4df-5379-48d7-a986-c0733ac27ddf.png)

**Comment by Tredeaux** [comment]
@OfferZenThrive I am busy updating this one.

**Comment by Tredeaux** [comment]
here we go

<img width="161" alt="image" src="https://user-images.githubusercontent.com/44365609/173058780-7cb657f2-86dc-42a5-80a9-328432c19eb5.png">

**Comment by OfferZenThrive** [comment]
Ah, that's perfect Tredeaux, thank you!
