### ISSUE TITLE
License for text 

### ISSUE THREAD

**Issue by eugene-sy** [OfferZen-Community/developer-mentoring#81]
Consider adding a license for the text materials.

The text in markdown files should not be considered code. Thus it should not fall under the MIT license clause. 
Usually, _content_ falls under knowledge-sharing, research, or literal creative works. The [CC](https://creativecommons.org) license should be a good choice.

**Comment by anelda** [comment]
A great resource, but I agree, adding a CC license would make it even more valuable.
