### ISSUE TITLE
Re: Types of Mentors

### ISSUE THREAD

**Issue by lasse-offerzen** [OfferZen-Community/developer-mentoring#82]
These last two mentor types (the Sponsor and the Affirmer) seem very similar to the Connector and the Coach respectively--consider combining or removing them?
<img width="894" alt="Screenshot 2022-06-21 at 09 47 12" src="https://user-images.githubusercontent.com/105852971/174745193-0e12153b-1604-48f5-ac1f-0ed864e2947e.png">

**Comment by michaelwiles** [comment]
Or possibly rewording their entries to make them more different... The words Sponsor has a different meaning to Connector and Coach also has a different meaning to Affirmer.
