### ISSUE TITLE
Basic Mentor Type Quiz

### ISSUE THREAD

**Issue by lasse-offerzen** [OfferZen-Community/developer-mentoring#94]
Aim: Help mentors identify which one of several mentor types to help them get more out of their mentoring experiences.

Need help with building out/integrating this quiz

Link to [Types of Mentors](https://www.developermentoring.guide/docs/getting-started-with-mentoring/For%20Mentors/types-of-mentors) page

**Quiz Structure:**

You are an **advisor** if you answer ‘yes’ to these questions:
- Do you feel that your experience entitles you to indicate how problems need to be solved? 
- Do you believe that reasonable solutions can be difficult to find, so you insist mentees follow your advice?
- Do you define mentoring as offering solutions to problems?

You are a **protector** if you answer ‘yes’ to these questions:
- Do you feel that your mentee needs you to step in and problem solve for them because they are overwhelmed?
- Do you offer solutions for your mentee's problems because you feel they lack an understanding of the big picture?
- Do you feel obligated to provide a safe space for your mentee to take risks?

You are a **coach** if you answer ‘yes’ to these questions:
- Do you like to let your mentee do most of the talking while you pinpoint ways to solve their problems?
- Do you find yourself pointing out weak and strong traits in your mentee?
- Are you aiming to help your mentee solve their problems?

You are a **connector** if you answer ‘yes’ to these questions:
- If you recognize a shortcoming in your mentee, do you try and connect them with experts in that area?
- Do you look for learning opportunities that will benefit your mentee?
- Do you have an extensive network that you can call on to help your mentee develop?

You are a **challenger** if you answer ‘yes’ to these questions:
- Do you enjoy playing the devil’s advocate to challenge your mentee?
- Do you encourage your mentee to aim high?
- Do you like to push your mentee further to help them develop independence?

You are a **clarifier** if you answer ‘yes’ to these questions:
- Do you help your mentee learn organizational values and politics?
- Do you allow your mentee to solve their problems?
- Are you slow to offer your opinion on how a mentee should handle a challenge?

You are a **sponsor** if you answer ‘yes’ to these questions:
- Do you find yourself recommending your mentee for promotion?
- Do you use your network connections to help your mentee get ahead?
- Do you suggest possible career opportunities to your mentee?

You are an **affirmer** if you answer ‘yes’ to these questions:
- If you see your mentee is worried about something, you spend a lot of time talking about it.
- Do you find yourself having a deep understanding and empathy for your mentee’s situation?
- Are you ready to offer support and a listening ear whenever your mentee stops by?

**Comment by JasonTame** [comment]
@lasse-offerzen Interesting idea! Do you think something similar to [this developer type quiz](https://www.12types.dev/quiz) could work?

**Comment by lasse-offerzen** [comment]
Hey @JasonTame ! Could do—is it possible to have the quiz work inside docusaurus? (and not have it redirect somewhere else?)

**Comment by JasonTame** [comment]
@lasse-offerzen Yup sure, it can be a custom component within docusaurus - the example quiz was just a layout example. It's highly likely that people will end up with multiple mentor types depending on how they answer the questions so I like the way it presents the results as multiple pie charts.

![image](https://user-images.githubusercontent.com/15672948/182308530-dcf4d1ea-6b7f-4ce4-9237-3153491d2ccb.png)

I'm happy to take this issue on if no one has put their hand up for it already

**Comment by lasse-offerzen** [comment]
@JasonTame Yes please! 🙏 🙏 🙏
