### ISSUE TITLE
Attachment Needed for Section "The Mentoring Agreement"

### ISSUE THREAD

**Issue by lasse-offerzen** [OfferZen-Community/developer-mentoring#96]
Users should be able to download a copy of the mentoring agreement from this section (e.g., link or attachment)

**Comment by thaliapill** [comment]
@lasse-offerzen if its a link to the hubspot doc, users will have to provide their emails to unlock it. 
If its a static file, it won't be updated so could become obsolete asap. 

Was going to add a hyperlink to the bottom of the page
![Screenshot 2022-07-07 at 18 20 58](https://user-images.githubusercontent.com/104366647/177822692-4b2cc4ae-9280-4ae1-b1f6-4682fcb0bcd1.png)

**Comment by rikusv** [comment]
I'm not sure if it would be appropriate to require entering an email address to download an attachment from an open source community guide like this.

How is the attachment different from the mentoring agreement markdown document? Is it possible to make it a single document, to avoid duplicate maintenance?

**Comment by lasse-offerzen** [comment]
Thanks @thaliapill and @rikusv — No difference! The idea was just for them to be able to download it to complete on their end. Let me check with the team first and then I'll share the file to be attached :)

**Comment by lasse-offerzen** [comment]
We'd ideally love both these files available for download at the bottom of the exercise?
[Reflective Exercise for Developer Mentoring Guide (1).docx](https://github.com/OfferZen-Community/developer-mentorin
[Reflective Exercise for Developer Mentoring Guide.pdf](https://github.com/OfferZen-Community/developer-mentoring/files/9188398/Reflective.Exercise.for.Developer.Mentoring.Guide.pdf)
g/files/9188396/Reflective.Exercise.for.Developer.Mentoring.Guide.1.docx)

**Comment by lasse-offerzen** [comment]
[Reflective Exercise for Developer Mentoring Guide.pdf](https://github.com/OfferZen-Community/developer-mentoring/files/9188401/Reflective.Exercise.for.Developer.Mentoring.Guide.pdf)

**Comment by lasse-offerzen** [comment]
[Reflective+Exercise.docx](https://github.com/OfferZen-Community/developer-mentoring/files/9188410/Reflective%2BExercise.docx)

**Comment by lasse-offerzen** [comment]
[Attachment for Developer Mentoring Guide.docx](https://github.com/OfferZen-Community/developer-mentoring/files/9233877/Attachment.for.Developer.Mentoring.Guide.docx)
[Attachment for Developer Mentoring Guide.pdf](https://github.com/OfferZen-Community/developer-mentoring/files/9233878/Attachment.for.Developer.Mentoring.Guide.pdf)
